// <auto-generated />
using System;
using ColYrself.DataProvider.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColYrself.DataProvider.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116124253_AddConnectionId")]
    partial class AddConnectionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwords", (string)null);
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.RoomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RoomUser");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("meeting_invitations", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("meeting_invitations");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.User", "Organizer")
                        .WithMany("OrganizedMeetings")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Password", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.User", "User")
                        .WithMany("Passwords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Room", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.Meeting", "Meeting")
                        .WithOne("Room")
                        .HasForeignKey("ColYrself.DataProvider.Models.Database.Room", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.RoomUser", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.Room", "Room")
                        .WithMany("RoomUser")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColYrself.DataProvider.Models.Database.User", "User")
                        .WithOne("RoomUser")
                        .HasForeignKey("ColYrself.DataProvider.Models.Database.RoomUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("meeting_invitations", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColYrself.DataProvider.Models.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.Navigation("Room")
                        .IsRequired();
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Room", b =>
                {
                    b.Navigation("RoomUser");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.User", b =>
                {
                    b.Navigation("OrganizedMeetings");

                    b.Navigation("Passwords");

                    b.Navigation("RoomUser")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
