// <auto-generated />
using System;
using ColYrself.DataProvider.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColYrself.DataProvider.Migrations.Meeting
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20251127223110_FixDbErrorsMeetings")]
    partial class FixDbErrorsMeetings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("invitedIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("organizerId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("meetings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
