// <auto-generated />
using System;
using ColYrself.DataProvider.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColYrself.DataProvider.Migrations.Meeting
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20251112122509_AddNameToMeeting")]
    partial class AddNameToMeeting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("invitedIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("organizerId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("organizerId");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.Meeting", b =>
                {
                    b.HasOne("ColYrself.DataProvider.Models.Database.User", "organizer")
                        .WithMany("organizedMeetings")
                        .HasForeignKey("organizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organizer");
                });

            modelBuilder.Entity("ColYrself.DataProvider.Models.Database.User", b =>
                {
                    b.Navigation("organizedMeetings");
                });
#pragma warning restore 612, 618
        }
    }
}
